### ISSUE TITLE
config parsing in bridge/forward.py

### ISSUE THREAD

**Issue by fracai** [snicker/gntp-regrowl#3]
Line 68 of forward.py reads in the configuration file by joining the elements of the CONFIG_PATH array from cli.py

On the other hand, cli.py just passes in the array to parser.read().

The ConfigParser documentation indicates that read() will attempt to read each of the elements in the array. When I tested this it looks like this results in cli.py reading ~/.regrowl, while forward.py tries to read ~/.regrowl/.regrowl.

Unless there's something I'm missing, I think the 'join' shouldn't be there in forward.py.

I fixed this in my [fork](https://github.com/fracai/gntp-regrowl/commit/ddeeb9c756eeef8ea45e83321df3dd68309974e7), as well as some later changes to how the config is read.

Thanks for your work (specifically with prowl).

**Comment by tortoo** [comment]
@fracai Hi fracai, could you  please take a look at this, thanks a lot! Prowl can receive notifications but the url seemed not to be delivered when the message forwarded to prowl. The notification received in prowl does not contain url.
